motd=test
resource-pack=http://127.0.0.1:3000/resourcepacks/dist/TokControlKanit.zip
resource-pack-sha1=e5c4150167492c977ad6fafef19077076ac9da62
require-resource-pack=true
resource-pack-prompt=TokControl Kanit Font
